// packages/examples/typescript-react/src/Sponser.tsx
import React, { useState, useEffect } from 'react';
import glory from './cssRenderer'
import {
  Code
} from './StyledCode'
import {
  textStyle,
  h2Style,
  codeStyle,
  anchorStyle,
  containerStyle
} from './globalStyle'

const StyledText = ({children}) => {
  return (
    <p className={textStyle}>
    {children}
    </p>
  )
}

const StyledCode = ({children}) => {
  return (
    <Code className={codeStyle}>
    {children}
    </Code>
  )
}

const StyledAnchor = ({children, ...attrs}) => {
  return (
    <a className={anchorStyle} {...attrs}>
    {children}
    </a>
  )
}

const StyledImage = ({children, ...attrs}) => {
  return (
    <img className={glory.virtual({
      maxWidth: '300px',
      width: "100%",
      display: "block"
    })} {...attrs} />
  )
}

function Sponser(props) {
  return (
    <div className={containerStyle}>
    <h2 className={`${h2Style} ${glory.virtual({
      gridColumn: '1/-1'
    })}`}>Sponser</h2>
    <div>
    <StyledText>This application is sponsered by <StyledAnchor href="https://tecky.io/en/">Tecky Academy</StyledAnchor>.</StyledText>
    <a href="https://tecky.io/en/">
    <StyledImage src="/logo_title.png"/>
    </a>
    </div>
    <StyledText>This section uses <StyledCode>glory.jsx()</StyledCode> for styling.</StyledText>
    </div>
  )
}

export default Sponser;

// packages/examples/svelte/src/Sponser.svelte
<script>
  import {onMount} from 'svelte';
  import glory from './cssRenderer'
  import {
    textStyle,
    h2Style,
    codeStyle,
    anchorStyle,
    containerStyle,
    baseSize
  } from './globalStyle'
  import Code from './Code.svelte'

</script>

<div class={containerStyle}>
<h2 class={`${h2Style} ${glory.virtual({
  gridColumn: '1/-1'
})}`}>Sponser</h2>
<div>
<p class={textStyle}>This application is sponsered by <a class={anchorStyle} href="https://tecky.io/en/">Tecky Academy</a>.</p>
<a href="https://tecky.io/en/">
<img class={glory.virtual({
  maxWidth: '300px',
  width: "100%",
  display: "block"
})} src="/logo_title.png"/>
</a>
</div>
<div></div>
</div>
